clusterGroup:
  name: hub
  isHubCluster: true
  insecureUnsealVaultInsideCluster: true

  namespaces:
  - hive
  - vault
  - golang-external-secrets

  subscriptions:
    hive:
      name: hive
      namespace: hive
      channel: alpha
      #channel: ocm-2.4
      source: community-operators

  projects:
  - hub

  applications:
    vault:
      name: vault
      namespace: vault
      project: hub
      path: common/hashicorp-vault

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      path: common/golang-external-secrets

    prereq:
      name: cluster-template-service
      namespace: hive
      project: hub
      path: charts/service


  imperative:
    # For additional details, please refer to
    # https://hybrid-cloud-patterns.io/imperative-actions/#additional-job-customizations
    jobs:
    - name: regional-ca
      # ansible playbook to be run
      playbook: ansible/playbooks/on-hub-get-regional-ca.yml
      # per playbook timeout in seconds
      timeout: 234
      # verbosity: "-v"
