clusterGroup:
  name: hub
  isHubCluster: true
  insecureUnsealVaultInsideCluster: true

  namespaces:
  - hive
  - vault
  - hypershift
  - multicluster-engine
  - golang-external-secrets

  subscriptions:
    hive:
      name: hive
      namespace: openshift-operators
      channel: alpha
      #channel: ocm-2.4 # more stable?
      source: community-operators

    hypershift:
      name: multicluster-engine
      namespace: multicluster-engine
      channel: stable-2.1

  projects:
  - hub
  - demo

  applications:
    vault:
      project: hub
      name: vault
      namespace: vault
      path: common/hashicorp-vault

    golang-external-secrets:
      project: hub
      name: golang-external-secrets
      namespace: golang-external-secrets
      path: common/golang-external-secrets

    prereq:
      project: hub
      name: cluster-template-service
      namespace: hive
      path: charts/service

    clusters:
      project: demo
      name: hosted-clusters
      namespace: hypershift
      path: devconf-template/templates
      repoURL: https://github.com/rawagner/helm-demo/
      targetRevision: main

  imperative:
    # For additional details, please refer to
    # https://hybrid-cloud-patterns.io/imperative-actions/#additional-job-customizations
    jobs:
    - name: regional-ca
      # ansible playbook to be run
      playbook: ansible/playbooks/on-hub-get-regional-ca.yml
      # per playbook timeout in seconds
      timeout: 234
      # verbosity: "-v"
