clusterGroup:
  name: hub
  isHubCluster: true
  insecureUnsealVaultInsideCluster: true

  namespaces:
  - hive
  - vault
  - hypershift
  - multicluster-engine
  - golang-external-secrets

  subscriptions:
    hive:
      name: hive-operator
      namespace: openshift-operators
      channel: alpha
      #channel: ocm-2.4 # more stable?
      source: community-operators

    hypershift:
      name: multicluster-engine
      namespace: multicluster-engine
      channel: stable-2.1

    caas:
      name: cluster-aas-operator
      namespace: openshift-operators
      channel: alpha
      source: community-operators

  projects:
  - hub
  - demo

  applications:
    vault:
      project: hub
      name: vault
      namespace: vault
      path: common/hashicorp-vault

    golang-external-secrets:
      project: hub
      name: golang-external-secrets
      namespace: golang-external-secrets
      path: common/golang-external-secrets

    patterns:
      project: hub
      name: cluster-template-service
      namespace: hive
      path: charts/service

