# https://github.com/stolostron/hypershift-deployment-controller/blob/359179cd6b6e60d4999a9b0026f7ad6ecc39c925/docs/provision_hypershift_clusters_by_mce.md
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: HypershiftDeployment
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}
spec:
  hostingCluster: local-cluster
  hostingNamespace: clusters
  hostedClusterSpec:
    release:
      image: quay.io/openshift-release-dev/ocp-release:{{ .Values.ocpVersion }}-x86_64  
  infrastructure:
    cloudProvider:
      name: {{ .Values.infra.creds }}
    configure: True
    platform:
      aws:
        region: {{ .Values.infra.region }}
