apiVersion: hypershift.openshift.io/v1alpha1
kind: HostedCluster
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}
spec:
  release:
    image: quay.io/openshift-release-dev/ocp-release:{{ .Values.ocpVersion }}-x86_64
  pullSecret:
    name: {{ .pullSecretName }}
  sshKey:
    name: {{ .sshSecretName }}
  networking:
    clusterNetwork:
    - cidr: 10.132.0.0/14
    serviceNetwork:
    - cidr: 172.31.0.0/16
    machineNetwork:
    - cidr: 192.168.122.0/24
    networkType: OVNKubernetes
  platform:
    type: Agent
    agent:
      agentNamespace: devconf-infra
  infraID: {{ .Release.Name }}
  dns:
    baseDomain: {{ .Values.baseDomain }}
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route
