global:
  dummy: 0

infra:
  name: hypershift
  region: ap-southeast-2
  location: north-pole
  baseDomain: blueprints.rhecoeng.com

patterns:
- name: xray
  repo: https://github.com/hybrid-cloud-patterns/medical-diagnosis/
  deploy: false
- name: bobbycar
  repo: https://github.com/hybrid-cloud-patterns/connected-vehicle-architecture/
  deploy: true

secretStore:
  name: vault-backend
  kind: ClusterSecretStore
