# https://github.com/stolostron/hypershift-deployment-controller/blob/359179cd6b6e60d4999a9b0026f7ad6ecc39c925/docs/provision_hypershift_clusters_by_mce.md
---
# For use when manually creating clusters with ACM
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.infra.name }}-infra-creds
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec: 
  data:
  - secretKey: openshiftPullSecret
    remoteRef:
      key: {{ default "secret/data/hub/openshiftPullSecret" .pullSecretKeyPath }}
      property: content
  - secretKey: awsKeyId
    remoteRef:
      key: {{ default "secret/data/hub/aws" .awsKeyPath }}
      property: access_key_id
  - secretKey: awsAccessKey
    remoteRef:
      key: {{ default "secret/data/hub/aws" .awsKeyPath }}
      property: secret_access_key
  - secretKey: sshPublicKey
    remoteRef:
      key: {{ default "secret/data/hub/publickey" .sshPublicKeyPath }}
      property: content
  - secretKey: sshPrivateKey
    remoteRef:
      key: {{ default "secret/data/hub/privatekey" .sshPrivateKeyPath }}
      property: content
  refreshInterval: 24h0m0s
  secretStoreRef: 
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ .Values.infra.name }}-infra-creds
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          cluster.open-cluster-management.io/credentials: ""
          cluster.open-cluster-management.io/type: aws
      data:
        baseDomain: "{{ $.Values.infra.baseDomain }}"
        pullSecret: |-
          {{ "{{ .openshiftPullSecret | toString }}" }}
        aws_access_key_id: |-
          {{ "{{ .awsKeyId | toString }}" }}
        aws_secret_access_key: |-
          {{ "{{ .awsAccessKey | toString }}" }}
        ssh-privatekey: |-
          {{ "{{ .sshPrivateKey | toString }}" }}
        ssh-publickey: |-
          {{ "{{ .sshPublicKey | toString }}" }}
---
# For use when manually creating clusters with ACM
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hypershift-operator-oidc-provider-s3-credentials
  namespace: local-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec: 
  data:
  - secretKey: awsKeyId
    remoteRef:
      key: {{ default "secret/data/hub/aws" .awsKeyPath }}
      property: access_key_id
  - secretKey: awsAccessKey
    remoteRef:
      key: {{ default "secret/data/hub/aws" .awsKeyPath }}
      property: secret_access_key
  - secretKey: awsBucketName
    remoteRef:
      key: {{ default "secret/data/hub/aws" .awsKeyPath }}
      property: bucket_name
  - secretKey: awsBucketRegion
    remoteRef:
      key: {{ default "secret/data/hub/aws" .awsKeyPath }}
      property: bucket_region
  refreshInterval: 24h0m0s
  secretStoreRef: 
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: hypershift-operator-oidc-provider-s3-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        bucket: |-
          {{ "{{ .awsBucketName | toString }}" }}
        region: |-
          {{ "{{ .awsBucketRegion | toString }}" }}
        aws_access_key_id: |-
          {{ "{{ .awsKeyId | toString }}" }}
        aws_secret_access_key: |-
          {{ "{{ .awsAccessKey | toString }}" }}

# The bucket field contains an S3 bucket with public access to host OIDC
#  discovery documents for your HyperShift clusters.
#
# BUCKET_NAME=your-bucket-name
# aws s3api create-bucket --acl public-read --bucket $BUCKET_NAME --region $BUCKET_REGION
