apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  name: hive
spec:
  logLevel: debug
  targetNamespace: hive
---
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec:
  overrides:
    components:
    - name: hypershift-preview
      enabled: true
    - name: assisted-service
      enabled: true
    - name: cluster-lifecycle
      enabled: true
    - name: cluster-manager
      enabled: true
    - name: discovery
      enabled: true
    - name: hive
      enabled: true
    - name: server-foundation
      enabled: true
    - name: cluster-proxy-addon
      enabled: false
    - name: managedserviceaccount-preview
      enabled: true
    - name: console-mce
      enabled: true
