apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  name: hive
spec:
  logLevel: debug
  targetNamespace: hive
---
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec:
  overrides:
    components:
    - name: hypershift-preview
      enabled: true
    - name: assisted-service
      enabled: true
    - name: cluster-lifecycle
      enabled: true
    - name: cluster-manager
      enabled: true
    - name: discovery
      enabled: true
    - name: hive
      enabled: true
    - name: server-foundation
      enabled: true
    - name: cluster-proxy-addon
      enabled: false
    - name: managedserviceaccount-preview
      enabled: true
    - name: console-mce
      enabled: true
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    local-cluster: "true"
    cloud: auto-detect
    vendor: auto-detect
  name: local-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  hubAcceptsClient: true
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: managed-serviceaccount
  namespace: local-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  installNamespace: open-cluster-management-agent-addon