apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  name: hive
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  logLevel: debug
  targetNamespace: hive
---
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  availabilityConfig: High
  overrides:
    components:
      - name: hypershift-preview
        enabled: true
      - name: assisted-service
        enabled: true
      - name: cluster-lifecycle
        enabled: true
      - name: cluster-manager
        enabled: true
      - name: discovery
        enabled: true
      - name: hive
        enabled: true
      - name: server-foundation
        enabled: true
      - name: cluster-proxy-addon
        enabled: false
      - name: managedserviceaccount-preview
        enabled: false
      - name: console-mce
        enabled: true
  targetNamespace: multicluster-engine
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    local-cluster: "true"
    cloud: auto-detect
    vendor: auto-detect
  name: local-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
#  managedClusterClientConfigs:
#    - caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNakNDQWhxZ0F3SUJBZ0lJQ1ZZUWhjVy9ENUl3RFFZSktvWklodmNOQVFFTEJRQXdOekVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1TRXdId1lEVlFRREV4aHJkV0psTFdGd2FYTmxjblpsY2kxc...
#  url: https://api.template-hub.blueprints.rhecoeng.com:6443
---
apiVersion: internal.open-cluster-management.io/v1beta1
kind: ManagedClusterInfo
metadata:
  labels:
    local-cluster: "true"
    name: local-cluster
    vendor: OpenShift
  name: local-cluster
  namespace: local-cluster
spec: {}
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: hypershift-addon
  namespace: local-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  installNamespace: open-cluster-management-agent-addon
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: work-manager
  namespace: local-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  installNamespace: open-cluster-management-agent-addon
