apiVersion: clustertemplate.openshift.io/v1alpha1
kind: ClusterTemplateQuota
metadata:
  name: demo-quota
spec:
  budget: 5
  allowedTemplates:
  - name: hypershift-xray
  - name: hypershift-bobbycar
