---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: hypershift-sshkey-external-secret
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  data:
  - secretKey: sshPrivateKey
    remoteRef:
      key: {{ default "secret/data/hub/privatekey" .sshPrivateKeyPath }}
      property: content
  target:
    name: hypershift-sshkey
    template:
      type: Opaque
      data:
        ssh-privatekey: |-
          {{ "{{ .sshPrivateKey | toString }}" }}  
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: hypershift-pull-external-secret
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  data:
  - secretKey: openshiftPullSecret
    remoteRef:
      key: {{ default "secret/data/hub/openshiftPullSecret" .pullSecretKeyPath }}
      property: content
  target:
    name: hypershift-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {{ "{{ .openshiftPullSecret | toString }}" }}
